import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FontAwesomeService {

  constructor() {
   }

  fab = ['fa-500px', 'fa-accessible-icon', 'fa-accusoft', 'fa-acquisitions-incorporated',
  'fa-adn', 'fa-adversal', 'fa-affiliatetheme', 'fa-airbnb', 'fa-algolia', 'fa-alipay',
  'fa-amazon-pay', 'fa-amazon', 'fa-amilia', 'fa-android', 'fa-angellist', 'fa-angrycreative',
  'fa-angular', 'fa-app-store-ios', 'fa-app-store', 'fa-apper', 'fa-apple-pay', 'fa-apple', 'fa-artstation',
  'fa-asymmetrik', 'fa-atlassian', 'fa-audible', 'fa-autoprefixer', 'fa-avianex', 'fa-aviato', 'fa-aws', 'fa-bandcamp',
  'fa-battle-net', 'fa-behance-square', 'fa-behance', 'fa-bimobject', 'fa-bitbucket', 'fa-bitcoin', 'fa-bity', 'fa-black-tie',
  'fa-blackberry', 'fa-blogger-b', 'fa-blogger', 'fa-bluetooth-b', 'fa-bluetooth', 'fa-bootstrap', 'fa-btc', 'fa-buffer',
  'fa-buromobelexperte', 'fa-buy-n-large', 'fa-buysellads', 'fa-canadian-maple-leaf', 'fa-cc-amazon-pay', 'fa-cc-amex',
  'fa-cc-apple-pay', 'fa-cc-diners-club', 'fa-cc-discover', 'fa-cc-jcb', 'fa-cc-mastercard', 'fa-cc-paypal', 'fa-cc-stripe',
  'fa-cc-visa', 'fa-centercode', 'fa-centos', 'fa-chrome', 'fa-chromecast', 'fa-cloudflare', 'fa-cloudscale', 'fa-cloudsmith',
  'fa-cloudversify', 'fa-codepen', 'fa-codiepie', 'fa-confluence', 'fa-connectdevelop', 'fa-contao', 'fa-cotton-bureau',
  'fa-cpanel', 'fa-creative-commons-by', 'fa-creative-commons-nc-eu', 'fa-creative-commons-nc-jp', 'fa-creative-commons-nc',
  'fa-creative-commons-nd', 'fa-creative-commons-pd-alt', 'fa-creative-commons-pd', 'fa-creative-commons-remix',
  'fa-creative-commons-sa', 'fa-creative-commons-sampling-plus', 'fa-creative-commons-sampling', 'fa-creative-commons-share',
  'fa-creative-commons-zero', 'fa-creative-commons', 'fa-critical-role', 'fa-css3-alt', 'fa-css3', 'fa-cuttlefish',
  'fa-d-and-d-beyond', 'fa-d-and-d', 'fa-dailymotion', 'fa-dashcube', 'fa-deezer', 'fa-delicious', 'fa-deploydog',
  'fa-deskpro', 'fa-dev', 'fa-deviantart', 'fa-dhl', 'fa-diaspora', 'fa-digg', 'fa-digital-ocean', 'fa-discord',
  'fa-discourse', 'fa-dochub', 'fa-docker', 'fa-draft2digital', 'fa-dribbble-square', 'fa-dribbble', 'fa-dropbox',
  'fa-drupal', 'fa-dyalog', 'fa-earlybirds', 'fa-ebay', 'fa-edge-legacy', 'fa-edge', 'fa-elementor', 'fa-ello',
  'fa-ember', 'fa-empire', 'fa-envira', 'fa-erlang', 'fa-ethereum', 'fa-etsy', 'fa-evernote', 'fa-expeditedssl',
  'fa-facebook-f', 'fa-facebook-messenger', 'fa-facebook-square', 'fa-facebook', 'fa-fantasy-flight-games', 'fa-fedex',
  'fa-fedora', 'fa-figma', 'fa-firefox-browser', 'fa-firefox', 'fa-first-order-alt', 'fa-first-order', 'fa-firstdraft',
  'fa-flickr', 'fa-flipboard', 'fa-fly', 'fa-font-awesome-alt', 'fa-font-awesome-flag', 'fa-font-awesome-logo-full',
  'fa-font-awesome', 'fa-fonticons-fi', 'fa-fonticons', 'fa-fort-awesome-alt', 'fa-fort-awesome', 'fa-forumbee',
  'fa-foursquare', 'fa-free-code-camp', 'fa-freebsd', 'fa-fulcrum', 'fa-galactic-republic', 'fa-galactic-senate',
  'fa-get-pocket', 'fa-gg-circle', 'fa-gg', 'fa-git-alt', 'fa-git-square', 'fa-git', 'fa-github-alt', 'fa-github-square',
  'fa-github', 'fa-gitkraken', 'fa-gitlab', 'fa-gitter', 'fa-glide-g', 'fa-glide', 'fa-gofore', 'fa-goodreads-g', 'fa-goodreads',
  'fa-google-drive', 'fa-google-pay', 'fa-google-play', 'fa-google-plus-g', 'fa-google-plus-square', 'fa-google-plus',
  'fa-google-wallet', 'fa-google', 'fa-gratipay', 'fa-grav', 'fa-gripfire', 'fa-grunt', 'fa-guilded', 'fa-gulp',
  'fa-hacker-news-square', 'fa-hacker-news', 'fa-hackerrank', 'fa-hips', 'fa-hire-a-helper', 'fa-hive', 'fa-hooli',
  'fa-hornbill', 'fa-hotjar', 'fa-houzz', 'fa-html5', 'fa-hubspot', 'fa-ideal', 'fa-imdb', 'fa-innosoft', 'fa-instagram-square',
  'fa-instagram', 'fa-instalod', 'fa-intercom', 'fa-internet-explorer', 'fa-invision', 'fa-ioxhost', 'fa-itch-io',
  'fa-itunes-note', 'fa-itunes', 'fa-java', 'fa-jedi-order', 'fa-jenkins', 'fa-jira', 'fa-joget', 'fa-joomla', 'fa-js-square',
  'fa-js', 'fa-jsfiddle', 'fa-kaggle', 'fa-keybase', 'fa-keycdn', 'fa-kickstarter-k', 'fa-kickstarter', 'fa-korvue', 'fa-laravel',
  'fa-lastfm-square', 'fa-lastfm', 'fa-leanpub', 'fa-less', 'fa-line', 'fa-linkedin-in', 'fa-linkedin', 'fa-linode', 'fa-linux',
  'fa-lyft', 'fa-magento', 'fa-mailchimp', 'fa-mandalorian', 'fa-markdown', 'fa-mastodon', 'fa-maxcdn', 'fa-mdb', 'fa-medapps',
  'fa-medium-m', 'fa-medium', 'fa-medrt', 'fa-meetup', 'fa-megaport', 'fa-mendeley', 'fa-microblog', 'fa-microsoft', 'fa-mix',
  'fa-mixcloud', 'fa-mixer', 'fa-mizuni', 'fa-modx', 'fa-monero', 'fa-napster', 'fa-neos', 'fa-nimblr', 'fa-node-js', 'fa-node',
  'fa-npm', 'fa-ns8', 'fa-nutritionix', 'fa-octopus-deploy', 'fa-odnoklassniki-square', 'fa-odnoklassniki', 'fa-old-republic',
  'fa-opencart', 'fa-openid', 'fa-opera', 'fa-optin-monster', 'fa-orcid', 'fa-osi', 'fa-page4', 'fa-pagelines', 'fa-palfed',
  'fa-patreon', 'fa-paypal', 'fa-penny-arcade', 'fa-perbyte', 'fa-periscope', 'fa-phabricator', 'fa-phoenix-framework',
  'fa-phoenix-squadron', 'fa-php', 'fa-pied-piper-alt', 'fa-pied-piper-hat', 'fa-pied-piper-pp', 'fa-pied-piper-square',
  'fa-pied-piper', 'fa-pinterest-p', 'fa-pinterest-square', 'fa-pinterest', 'fa-playstation', 'fa-product-hunt', 'fa-pushed',
  'fa-python', 'fa-qq', 'fa-quinscape', 'fa-quora', 'fa-r-project', 'fa-raspberry-pi', 'fa-ravelry', 'fa-react', 'fa-reacteurope',
  'fa-readme', 'fa-rebel', 'fa-red-river', 'fa-reddit-alien', 'fa-reddit-square', 'fa-reddit', 'fa-redhat', 'fa-renren',
  'fa-replyd', 'fa-researchgate', 'fa-resolving', 'fa-rev', 'fa-rocketchat', 'fa-rockrms', 'fa-rust', 'fa-safari',
  'fa-salesforce', 'fa-sass', 'fa-schlix', 'fa-scribd', 'fa-searchengin', 'fa-sellcast', 'fa-sellsy', 'fa-servicestack',
  'fa-shirtsinbulk', 'fa-shopify', 'fa-shopware', 'fa-simplybuilt', 'fa-sistrix', 'fa-sith', 'fa-sketch', 'fa-skyatlas',
  'fa-skype', 'fa-slack-hash', 'fa-slack', 'fa-slideshare', 'fa-snapchat-ghost', 'fa-snapchat-square', 'fa-snapchat',
  'fa-soundcloud', 'fa-sourcetree', 'fa-speakap', 'fa-speaker-deck', 'fa-spotify', 'fa-squarespace', 'fa-stack-exchange',
  'fa-stack-overflow', 'fa-stackpath', 'fa-staylinked', 'fa-steam-square', 'fa-steam-symbol', 'fa-steam', 'fa-sticker-mule',
  'fa-strava', 'fa-stripe-s', 'fa-stripe', 'fa-studiovinari', 'fa-stumbleupon-circle', 'fa-stumbleupon', 'fa-superpowers',
  'fa-supple', 'fa-suse', 'fa-swift', 'fa-symfony', 'fa-teamspeak', 'fa-telegram-plane', 'fa-telegram', 'fa-tencent-weibo',
  'fa-the-red-yeti', 'fa-themeco', 'fa-themeisle', 'fa-think-peaks', 'fa-tiktok', 'fa-trade-federation', 'fa-trello',
  'fa-tripadvisor', 'fa-tumblr-square', 'fa-tumblr', 'fa-twitch', 'fa-twitter-square', "fa-twitter","fa-typo3","fa-uber",
  "fa-ubuntu","fa-uikit","fa-umbraco","fa-uncharted","fa-uniregistry","fa-unity","fa-unsplash","fa-untappd","fa-ups","fa-usb",
  "fa-usps","fa-ussunnah","fa-vaadin","fa-viacoin","fa-viadeo-square","fa-viadeo","fa-viber","fa-vimeo-square","fa-vimeo-v",
  "fa-vimeo","fa-vine","fa-vk","fa-vnv","fa-vuejs","fa-watchman-monitoring","fa-waze","fa-weebly","fa-weibo","fa-weixin",
  "fa-whatsapp-square","fa-whatsapp","fa-whmcs","fa-wikipedia-w","fa-windows","fa-wix","fa-wizards-of-the-coast","fa-wodu",
  "fa-wolf-pack-battalion","fa-wordpress-simple","fa-wordpress","fa-wpbeginner","fa-wpexplorer","fa-wpforms","fa-wpressr",
  "fa-xbox","fa-xing-square","fa-xing","fa-y-combinator","fa-yahoo","fa-yammer","fa-yandex-international","fa-yandex","fa-yarn",
  "fa-yelp","fa-yoast","fa-youtube-square","fa-youtube","fa-zhihu"]

fas = ["fa-address-book","fa-address-card","fa-angry",
"fa-arrow-alt-circle-down","fa-arrow-alt-circle-left","fa-arrow-alt-circle-right","fa-arrow-alt-circle-up","fa-bell-slash",
"fa-bell","fa-bookmark","fa-building","fa-calendar-alt","fa-calendar-check","fa-calendar-minus","fa-calendar-plus",
"fa-calendar-times","fa-calendar","fa-caret-square-down","fa-caret-square-left","fa-caret-square-right","fa-caret-square-up",
"fa-chart-bar","fa-check-circle","fa-check-square","fa-circle","fa-clipboard","fa-clock","fa-clone","fa-closed-captioning",
"fa-comment-alt","fa-comment-dots","fa-comment","fa-comments","fa-compass","fa-copy","fa-copyright","fa-credit-card","fa-dizzy",
"fa-dot-circle","fa-edit","fa-envelope-open","fa-envelope","fa-eye-slash","fa-eye","fa-file-alt","fa-file-archive","fa-file-audio",
"fa-file-code","fa-file-excel","fa-file-image","fa-file-pdf","fa-file-powerpoint","fa-file-video","fa-file-word","fa-file",
"fa-flag","fa-flushed","fa-folder-open","fa-folder","fa-font-awesome-logo-full","fa-frown-open","fa-frown","fa-futbol","fa-gem",
"fa-grimace","fa-grin-alt","fa-grin-beam-sweat","fa-grin-beam","fa-grin-hearts","fa-grin-squint-tears","fa-grin-squint",
"fa-grin-stars","fa-grin-tears","fa-grin-tongue-squint","fa-grin-tongue-wink","fa-grin-tongue","fa-grin-wink","fa-grin",
"fa-hand-lizard","fa-hand-paper","fa-hand-peace","fa-hand-point-down","fa-hand-point-left","fa-hand-point-right",
"fa-hand-point-up","fa-hand-pointer","fa-hand-rock","fa-hand-scissors","fa-hand-spock","fa-handshake","fa-hdd","fa-heart",
"fa-hospital","fa-hourglass","fa-id-badge","fa-id-card","fa-image","fa-images","fa-keyboard","fa-kiss-beam","fa-kiss-wink-heart",
"fa-kiss","fa-laugh-beam","fa-laugh-squint","fa-laugh-wink","fa-laugh","fa-lemon","fa-life-ring","fa-lightbulb","fa-list-alt",
"fa-map","fa-meh-blank","fa-meh-rolling-eyes","fa-meh","fa-minus-square","fa-money-bill-alt","fa-moon","fa-newspaper",
"fa-object-group","fa-object-ungroup","fa-paper-plane","fa-pause-circle","fa-play-circle","fa-plus-square","fa-question-circle",
"fa-registered","fa-sad-cry","fa-sad-tear","fa-save","fa-share-square","fa-smile-beam","fa-smile-wink","fa-smile","fa-snowflake",
"fa-square","fa-star-half","fa-star","fa-sticky-note","fa-stop-circle","fa-sun","fa-surprise","fa-thumbs-down","fa-thumbs-up",
"fa-times-circle","fa-tired","fa-trash-alt","fa-user-circle","fa-user","fa-window-close","fa-window-maximize","fa-window-minimize",
"fa-window-restore","fa-ad","fa-address-book","fa-address-card","fa-adjust","fa-air-freshener","fa-align-center",
"fa-align-justify","fa-align-left","fa-align-right","fa-allergies","fa-ambulance","fa-american-sign-language-interpreting",
"fa-anchor","fa-angle-double-down","fa-angle-double-left","fa-angle-double-right","fa-angle-double-up","fa-angle-down",
"fa-angle-left","fa-angle-right","fa-angle-up","fa-angry","fa-ankh","fa-apple-alt","fa-archive","fa-archway",
"fa-arrow-alt-circle-down","fa-arrow-alt-circle-left","fa-arrow-alt-circle-right","fa-arrow-alt-circle-up",
"fa-arrow-circle-down","fa-arrow-circle-left","fa-arrow-circle-right","fa-arrow-circle-up","fa-arrow-down","fa-arrow-left",
"fa-arrow-right","fa-arrow-up","fa-arrows-alt-h","fa-arrows-alt-v","fa-arrows-alt","fa-assistive-listening-systems",
"fa-asterisk","fa-at","fa-atlas","fa-atom","fa-audio-description","fa-award","fa-baby-carriage","fa-baby","fa-backspace",
"fa-backward","fa-bacon","fa-bacteria","fa-bacterium","fa-bahai","fa-balance-scale-left","fa-balance-scale-right",
"fa-balance-scale","fa-ban","fa-band-aid","fa-barcode","fa-bars","fa-baseball-ball","fa-basketball-ball","fa-bath",
"fa-battery-empty","fa-battery-full","fa-battery-half","fa-battery-quarter","fa-battery-three-quarters","fa-bed","fa-beer",
"fa-bell-slash","fa-bell","fa-bezier-curve","fa-bible","fa-bicycle","fa-biking","fa-binoculars","fa-biohazard","fa-birthday-cake",
"fa-blender-phone","fa-blender","fa-blind","fa-blog","fa-bold","fa-bolt","fa-bomb","fa-bone","fa-bong","fa-book-dead",
"fa-book-medical","fa-book-open","fa-book-reader","fa-book","fa-bookmark","fa-border-all","fa-border-none","fa-border-style",
"fa-bowling-ball","fa-box-open","fa-box-tissue","fa-box","fa-boxes","fa-braille","fa-brain","fa-bread-slice",
"fa-briefcase-medical","fa-briefcase","fa-broadcast-tower","fa-broom","fa-brush","fa-bug","fa-building","fa-bullhorn",
"fa-bullseye","fa-burn","fa-bus-alt","fa-bus","fa-business-time","fa-calculator","fa-calendar-alt","fa-calendar-check",
"fa-calendar-day","fa-calendar-minus","fa-calendar-plus","fa-calendar-times","fa-calendar-week","fa-calendar","fa-camera-retro",
"fa-camera","fa-campground","fa-candy-cane","fa-cannabis","fa-capsules","fa-car-alt","fa-car-battery","fa-car-crash",
"fa-car-side","fa-car","fa-caravan","fa-caret-down","fa-caret-left","fa-caret-right","fa-caret-square-down",
"fa-caret-square-left","fa-caret-square-right","fa-caret-square-up","fa-caret-up","fa-carrot","fa-cart-arrow-down",
"fa-cart-plus","fa-cash-register","fa-cat","fa-certificate","fa-chair","fa-chalkboard-teacher","fa-chalkboard",
"fa-charging-station","fa-chart-area","fa-chart-bar","fa-chart-line","fa-chart-pie","fa-check-circle","fa-check-double",
"fa-check-square","fa-check","fa-cheese","fa-chess-bishop","fa-chess-board","fa-chess-king","fa-chess-knight","fa-chess-pawn",
"fa-chess-queen","fa-chess-rook","fa-chess","fa-chevron-circle-down","fa-chevron-circle-left","fa-chevron-circle-right",
"fa-chevron-circle-up","fa-chevron-down","fa-chevron-left","fa-chevron-right","fa-chevron-up","fa-child","fa-church",
"fa-circle-notch","fa-circle","fa-city","fa-clinic-medical","fa-clipboard-check","fa-clipboard-list","fa-clipboard",
"fa-clock","fa-clone","fa-closed-captioning","fa-cloud-download-alt","fa-cloud-meatball","fa-cloud-moon-rain","fa-cloud-moon",
"fa-cloud-rain","fa-cloud-showers-heavy","fa-cloud-sun-rain","fa-cloud-sun","fa-cloud-upload-alt","fa-cloud","fa-cocktail",
"fa-code-branch","fa-code","fa-coffee","fa-cog","fa-cogs","fa-coins","fa-columns","fa-comment-alt","fa-comment-dollar",
"fa-comment-dots","fa-comment-medical","fa-comment-slash","fa-comment","fa-comments-dollar","fa-comments","fa-compact-disc",
"fa-compass","fa-compress-alt","fa-compress-arrows-alt","fa-compress","fa-concierge-bell","fa-cookie-bite","fa-cookie","fa-copy",
"fa-copyright","fa-couch","fa-credit-card","fa-crop-alt","fa-crop","fa-cross","fa-crosshairs","fa-crow","fa-crown","fa-crutch",
"fa-cube","fa-cubes","fa-cut","fa-database","fa-deaf","fa-democrat","fa-desktop","fa-dharmachakra","fa-diagnoses","fa-dice-d20",
"fa-dice-d6","fa-dice-five","fa-dice-four","fa-dice-one","fa-dice-six","fa-dice-three","fa-dice-two","fa-dice",
"fa-digital-tachograph","fa-directions","fa-disease","fa-divide","fa-dizzy","fa-dna","fa-dog","fa-dollar-sign","fa-dolly-flatbed",
"fa-dolly","fa-donate","fa-door-closed","fa-door-open","fa-dot-circle","fa-dove","fa-download","fa-drafting-compass","fa-dragon",
"fa-draw-polygon","fa-drum-steelpan","fa-drum","fa-drumstick-bite","fa-dumbbell","fa-dumpster-fire","fa-dumpster","fa-dungeon",
"fa-edit","fa-egg","fa-eject","fa-ellipsis-h","fa-ellipsis-v","fa-envelope-open-text","fa-envelope-open","fa-envelope-square",
"fa-envelope","fa-equals","fa-eraser","fa-ethernet","fa-euro-sign","fa-exchange-alt","fa-exclamation-circle",
"fa-exclamation-triangle","fa-exclamation","fa-expand-alt","fa-expand-arrows-alt","fa-expand","fa-external-link-alt",
"fa-external-link-square-alt","fa-eye-dropper","fa-eye-slash","fa-eye","fa-fan","fa-fast-backward","fa-fast-forward",
"fa-faucet","fa-fax","fa-feather-alt","fa-feather","fa-female","fa-fighter-jet","fa-file-alt","fa-file-archive",
"fa-file-audio","fa-file-code","fa-file-contract","fa-file-csv","fa-file-download","fa-file-excel","fa-file-export",
"fa-file-image","fa-file-import","fa-file-invoice-dollar","fa-file-invoice","fa-file-medical-alt","fa-file-medical",
"fa-file-pdf","fa-file-powerpoint","fa-file-prescription","fa-file-signature","fa-file-upload","fa-file-video","fa-file-word",
"fa-file","fa-fill-drip","fa-fill","fa-film","fa-filter","fa-fingerprint","fa-fire-alt","fa-fire-extinguisher","fa-fire",
"fa-first-aid","fa-fish","fa-fist-raised","fa-flag-checkered","fa-flag-usa","fa-flag","fa-flask","fa-flushed","fa-folder-minus","fa-folder-open","fa-folder-plus","fa-folder","fa-font-awesome-logo-full","fa-font","fa-football-ball","fa-forward","fa-frog","fa-frown-open","fa-frown","fa-funnel-dollar","fa-futbol","fa-gamepad","fa-gas-pump","fa-gavel","fa-gem","fa-genderless","fa-ghost","fa-gift","fa-gifts","fa-glass-cheers","fa-glass-martini-alt","fa-glass-martini","fa-glass-whiskey","fa-glasses","fa-globe-africa","fa-globe-americas","fa-globe-asia","fa-globe-europe","fa-globe","fa-golf-ball","fa-gopuram","fa-graduation-cap","fa-greater-than-equal","fa-greater-than","fa-grimace","fa-grin-alt","fa-grin-beam-sweat","fa-grin-beam","fa-grin-hearts","fa-grin-squint-tears","fa-grin-squint","fa-grin-stars","fa-grin-tears","fa-grin-tongue-squint","fa-grin-tongue-wink","fa-grin-tongue","fa-grin-wink","fa-grin","fa-grip-horizontal","fa-grip-lines-vertical","fa-grip-lines","fa-grip-vertical","fa-guitar","fa-h-square","fa-hamburger","fa-hammer","fa-hamsa","fa-hand-holding-heart","fa-hand-holding-medical","fa-hand-holding-usd","fa-hand-holding-water","fa-hand-holding","fa-hand-lizard","fa-hand-middle-finger","fa-hand-paper","fa-hand-peace","fa-hand-point-down","fa-hand-point-left","fa-hand-point-right","fa-hand-point-up","fa-hand-pointer","fa-hand-rock","fa-hand-scissors","fa-hand-sparkles","fa-hand-spock","fa-hands-helping","fa-hands-wash","fa-hands","fa-handshake-alt-slash","fa-handshake-slash","fa-handshake","fa-hanukiah","fa-hard-hat","fa-hashtag","fa-hat-cowboy-side","fa-hat-cowboy","fa-hat-wizard","fa-hdd","fa-head-side-cough-slash","fa-head-side-cough","fa-head-side-mask","fa-head-side-virus","fa-heading","fa-headphones-alt","fa-headphones","fa-headset","fa-heart-broken","fa-heart","fa-heartbeat","fa-helicopter","fa-highlighter","fa-hiking","fa-hippo","fa-history","fa-hockey-puck","fa-holly-berry","fa-home","fa-horse-head","fa-horse","fa-hospital-alt","fa-hospital-symbol","fa-hospital-user","fa-hospital","fa-hot-tub","fa-hotdog","fa-hotel","fa-hourglass-end","fa-hourglass-half","fa-hourglass-start","fa-hourglass","fa-house-damage","fa-house-user","fa-hryvnia","fa-i-cursor","fa-ice-cream","fa-icicles","fa-icons","fa-id-badge","fa-id-card-alt","fa-id-card","fa-igloo","fa-image","fa-images","fa-inbox","fa-indent","fa-industry","fa-infinity","fa-info-circle","fa-info","fa-italic","fa-jedi","fa-joint","fa-journal-whills","fa-kaaba","fa-key","fa-keyboard","fa-khanda","fa-kiss-beam","fa-kiss-wink-heart","fa-kiss","fa-kiwi-bird","fa-landmark","fa-language","fa-laptop-code","fa-laptop-house","fa-laptop-medical","fa-laptop","fa-laugh-beam","fa-laugh-squint","fa-laugh-wink","fa-laugh","fa-layer-group","fa-leaf","fa-lemon","fa-less-than-equal","fa-less-than","fa-level-down-alt","fa-level-up-alt","fa-life-ring","fa-lightbulb","fa-link","fa-lira-sign","fa-list-alt","fa-list-ol","fa-list-ul","fa-list","fa-location-arrow","fa-lock-open","fa-lock","fa-long-arrow-alt-down","fa-long-arrow-alt-left","fa-long-arrow-alt-right","fa-long-arrow-alt-up","fa-low-vision","fa-luggage-cart","fa-lungs-virus","fa-lungs","fa-magic","fa-magnet","fa-mail-bulk","fa-male","fa-map-marked-alt","fa-map-marked","fa-map-marker-alt","fa-map-marker","fa-map-pin","fa-map-signs","fa-map","fa-marker","fa-mars-double","fa-mars-stroke-h","fa-mars-stroke-v","fa-mars-stroke","fa-mars","fa-mask","fa-medal","fa-medkit","fa-meh-blank","fa-meh-rolling-eyes","fa-meh","fa-memory","fa-menorah","fa-mercury","fa-meteor","fa-microchip","fa-microphone-alt-slash","fa-microphone-alt","fa-microphone-slash","fa-microphone","fa-microscope","fa-minus-circle","fa-minus-square","fa-minus","fa-mitten","fa-mobile-alt","fa-mobile","fa-money-bill-alt","fa-money-bill-wave-alt","fa-money-bill-wave","fa-money-bill","fa-money-check-alt","fa-money-check","fa-monument","fa-moon","fa-mortar-pestle","fa-mosque","fa-motorcycle","fa-mountain","fa-mouse-pointer","fa-mouse","fa-mug-hot","fa-music","fa-network-wired","fa-neuter","fa-newspaper","fa-not-equal","fa-notes-medical","fa-object-group","fa-object-ungroup","fa-oil-can","fa-om","fa-otter","fa-outdent","fa-pager","fa-paint-brush","fa-paint-roller","fa-palette","fa-pallet","fa-paper-plane","fa-paperclip","fa-parachute-box","fa-paragraph","fa-parking","fa-passport","fa-pastafarianism","fa-paste","fa-pause-circle","fa-pause","fa-paw","fa-peace","fa-pen-alt","fa-pen-fancy","fa-pen-nib","fa-pen-square","fa-pen","fa-pencil-alt","fa-pencil-ruler","fa-people-arrows","fa-people-carry","fa-pepper-hot","fa-percent","fa-percentage","fa-person-booth","fa-phone-alt","fa-phone-slash","fa-phone-square-alt","fa-phone-square","fa-phone-volume","fa-phone","fa-photo-video","fa-piggy-bank","fa-pills","fa-pizza-slice","fa-place-of-worship","fa-plane-arrival","fa-plane-departure","fa-plane-slash","fa-plane","fa-play-circle","fa-play","fa-plug","fa-plus-circle","fa-plus-square","fa-plus","fa-podcast","fa-poll-h","fa-poll","fa-poo-storm","fa-poo","fa-poop","fa-portrait","fa-pound-sign","fa-power-off","fa-pray","fa-praying-hands","fa-prescription-bottle-alt","fa-prescription-bottle","fa-prescription","fa-print","fa-procedures","fa-project-diagram","fa-pump-medical","fa-pump-soap","fa-puzzle-piece","fa-qrcode","fa-question-circle","fa-question","fa-quidditch","fa-quote-left","fa-quote-right","fa-quran","fa-radiation-alt","fa-radiation","fa-rainbow","fa-random","fa-receipt","fa-record-vinyl","fa-recycle","fa-redo-alt","fa-redo","fa-registered","fa-remove-format","fa-reply-all","fa-reply","fa-republican","fa-restroom","fa-retweet","fa-ribbon","fa-ring","fa-road","fa-robot","fa-rocket","fa-route","fa-rss-square","fa-rss","fa-ruble-sign","fa-ruler-combined","fa-ruler-horizontal","fa-ruler-vertical","fa-ruler","fa-running","fa-rupee-sign","fa-sad-cry","fa-sad-tear","fa-satellite-dish","fa-satellite","fa-save","fa-school","fa-screwdriver","fa-scroll","fa-sd-card","fa-search-dollar","fa-search-location","fa-search-minus","fa-search-plus","fa-search","fa-seedling","fa-server","fa-shapes","fa-share-alt-square","fa-share-alt","fa-share-square","fa-share","fa-shekel-sign","fa-shield-alt","fa-shield-virus","fa-ship","fa-shipping-fast","fa-shoe-prints","fa-shopping-bag","fa-shopping-basket","fa-shopping-cart","fa-shower","fa-shuttle-van","fa-sign-in-alt","fa-sign-language","fa-sign-out-alt","fa-sign","fa-signal","fa-signature","fa-sim-card","fa-sink","fa-sitemap","fa-skating","fa-skiing-nordic","fa-skiing","fa-skull-crossbones","fa-skull","fa-slash","fa-sleigh","fa-sliders-h","fa-smile-beam","fa-smile-wink","fa-smile","fa-smog","fa-smoking-ban","fa-smoking","fa-sms","fa-snowboarding","fa-snowflake","fa-snowman","fa-snowplow","fa-soap","fa-socks","fa-solar-panel","fa-sort-alpha-down-alt","fa-sort-alpha-down","fa-sort-alpha-up-alt","fa-sort-alpha-up","fa-sort-amount-down-alt","fa-sort-amount-down","fa-sort-amount-up-alt","fa-sort-amount-up","fa-sort-down","fa-sort-numeric-down-alt","fa-sort-numeric-down","fa-sort-numeric-up-alt","fa-sort-numeric-up","fa-sort-up","fa-sort","fa-spa","fa-space-shuttle","fa-spell-check","fa-spider","fa-spinner","fa-splotch","fa-spray-can","fa-square-full","fa-square-root-alt","fa-square","fa-stamp","fa-star-and-crescent","fa-star-half-alt","fa-star-half","fa-star-of-david","fa-star-of-life","fa-star","fa-step-backward","fa-step-forward","fa-stethoscope","fa-sticky-note","fa-stop-circle","fa-stop","fa-stopwatch-20","fa-stopwatch","fa-store-alt-slash","fa-store-alt","fa-store-slash","fa-store","fa-stream","fa-street-view","fa-strikethrough","fa-stroopwafel","fa-subscript","fa-subway","fa-suitcase-rolling","fa-suitcase","fa-sun","fa-superscript","fa-surprise","fa-swatchbook","fa-swimmer","fa-swimming-pool","fa-synagogue","fa-sync-alt","fa-sync","fa-syringe","fa-table-tennis","fa-table","fa-tablet-alt","fa-tablet","fa-tablets","fa-tachometer-alt","fa-tag","fa-tags","fa-tape","fa-tasks","fa-taxi","fa-teeth-open","fa-teeth","fa-temperature-high","fa-temperature-low","fa-tenge","fa-terminal","fa-text-height","fa-text-width","fa-th-large","fa-th-list","fa-th","fa-theater-masks","fa-thermometer-empty","fa-thermometer-full","fa-thermometer-half","fa-thermometer-quarter","fa-thermometer-three-quarters","fa-thermometer","fa-thumbs-down","fa-thumbs-up","fa-thumbtack","fa-ticket-alt","fa-times-circle","fa-times","fa-tint-slash","fa-tint","fa-tired","fa-toggle-off","fa-toggle-on","fa-toilet-paper-slash","fa-toilet-paper","fa-toilet","fa-toolbox","fa-tools","fa-tooth","fa-torah","fa-torii-gate","fa-tractor","fa-trademark","fa-traffic-light","fa-trailer","fa-train","fa-tram","fa-transgender-alt","fa-transgender","fa-trash-alt","fa-trash-restore-alt","fa-trash-restore","fa-trash","fa-tree","fa-trophy","fa-truck-loading","fa-truck-monster","fa-truck-moving","fa-truck-pickup","fa-truck","fa-tshirt","fa-tty","fa-tv","fa-umbrella-beach","fa-umbrella","fa-underline","fa-undo-alt","fa-undo","fa-universal-access","fa-university","fa-unlink","fa-unlock-alt","fa-unlock","fa-upload","fa-user-alt-slash","fa-user-alt","fa-user-astronaut","fa-user-check","fa-user-circle","fa-user-clock","fa-user-cog","fa-user-edit","fa-user-friends","fa-user-graduate","fa-user-injured","fa-user-lock","fa-user-md","fa-user-minus","fa-user-ninja","fa-user-nurse","fa-user-plus","fa-user-secret","fa-user-shield","fa-user-slash","fa-user-tag","fa-user-tie","fa-user-times","fa-user","fa-users-cog","fa-users-slash","fa-users","fa-utensil-spoon","fa-utensils","fa-vector-square","fa-venus-double","fa-venus-mars","fa-venus","fa-vest-patches","fa-vest","fa-vial","fa-vials","fa-video-slash","fa-video","fa-vihara","fa-virus-slash","fa-virus","fa-viruses","fa-voicemail","fa-volleyball-ball","fa-volume-down","fa-volume-mute","fa-volume-off","fa-volume-up","fa-vote-yea","fa-vr-cardboard","fa-walking","fa-wallet","fa-warehouse","fa-water","fa-wave-square","fa-weight-hanging","fa-weight","fa-wheelchair","fa-wifi","fa-wind","fa-window-close","fa-window-maximize","fa-window-minimize","fa-window-restore",
"fa-wine-bottle","fa-wine-glass-alt","fa-wine-glass","fa-won-sign","fa-wrench","fa-x-ray","fa-yen-sign","fa-yin-yang"];

}
